server {
    listen 80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # Sirve estáticos si existen, si no, reescribe internamente solo una vez
    location / {
        try_files $uri $uri/ @rewrites;
    }

    # Punto de caída: solo aquí devolvemos index.html
    location @rewrites {
        # la directiva `break` evita entrar otra vez en location /
        rewrite ^ /index.html break;
    }

    # Caché para assets
    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|woff2?|ttf|eot)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    # Oculta la versión de Nginx
    server_tokens off;
}

